Feature/cadastrar usuario
projetoOpenSource/ms-agendamento-tarefa-gp1 pull request #1
Opened 2023-08-27 16:52 UTC by moriartynho

Por favor, verificar se as alterações de configuraçao são válidas.

Recurso de cadastro de usuário criado com as devidas validações, sendo possivel adicionar outras futuramente, se necessário.

2023-08-27 23:55 UTC, salatielfiore requested changes

2023-08-27 23:55 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/repository/UsuarioRepository.java
> +	Usuario findByEmail(String email);
Já que você que apenas verificar se existe o usuário com um determinado e-mail utiliza o existByEmail que ele retornará um valor booleano.

2023-08-27 23:55 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/service/cadastro/CadastroService.java
> +		repository.save(obj);
Se caso der um erro interno ou o banco de dados não estiver funcionando o sistema está preparado para tratar a exceção?

2023-08-27 23:55 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/service/cadastro/CadastroService.java
> +
Java doc

2023-08-27 23:55 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/service/cadastro/validacoes/ValidarSeSenhasCoincidem.java
> +			throw new RuntimeException("Senhas não coincidem");
Em vez de usar o runtime exceptio cria uma classe de exceção de validação tipo validateException que extends de Exception sobreescrevendo o construtor que passa uma mensagem como parametro.

Aproveita e cria o handle para mostras as mensagens de erros personalizadas.

`
@ControllerAdvice
public class ResourceExceptionHandler {

	/**
	 * Captura as Exceções do InternalErrorException
	 * 
	 * @param e
	 *            exceção que ocorreu ao axecutar alguma ação no sistema
	 * @param request
	 *            O contêiner do servlet cria um HttpServletRequest objeto e o passa como um argumento para os métodos de serviço do servlet
	 *            ( doGet, doPost, etc).
	 * @return ResponseEntity<ResponseMessageError>
	 */
	@ExceptionHandler(InternalErrorException.class)
	public ResponseEntity<ResponseMessageError> handleInternalError(InternalErrorException e, HttpServletRequest request) {
		return popularResponseMessageError(e, HttpStatus.INTERNAL_SERVER_ERROR.value(),
				messages.get("messages.handler.titulo.internalerror"), request);
	}

	/**
	 * Captura as Exceções do ValidationException
	 * 
	 * @param e
	 *            exceção que ocorreu ao axecutar alguma ação no sistema
	 * @param request
	 *            O contêiner do servlet cria um HttpServletRequest objeto e o passa como um argumento para os métodos de serviço do servlet
	 *            ( doGet, doPost, etc).
	 * @return ResponseEntity<ResponseMessageError>
	 */
	@ExceptionHandler(ValidationException.class)
	public ResponseEntity<ResponseMessageError> handleValidation(ValidationException e, HttpServletRequest request) {
		return popularResponseMessageError(e, HttpStatus.BAD_REQUEST.value(), messages.get("messages.handler.titulo.validation"), request);
	}

	/**
	 * Captura as Exceções do Exception
	 * 
	 * @param e
	 *            exceção que ocorreu ao axecutar alguma ação no sistema
	 * @param request
	 *            O contêiner do servlet cria um HttpServletRequest objeto e o passa como um argumento para os métodos de serviço do servlet
	 *            ( doGet, doPost, etc).
	 * @return ResponseEntity<ResponseMessageError>
	 */
	@ExceptionHandler(Exception.class)
	public ResponseEntity<ResponseMessageError> handleException(Exception e, HttpServletRequest request) {
		return popularResponseMessageError(e, HttpStatus.INTERNAL_SERVER_ERROR.value(), messages.get("messages.handler.titulo.exception"),
				request);
	}

	/**
	 * Método que popula o response para cada exceção.
	 * 
	 * @param e
	 *            exceção que ocorreu ao axecutar alguma ação no sistema
	 * @param status
	 *            status da exceção que ocorreu
	 * @param titulo
	 *            titulo da exceção que ocorreu
	 * @param request
	 *            O contêiner do servlet cria um HttpServletRequest objeto e o passa como um argumento para os métodos de serviço do servlet
	 *            ( doGet, doPost, etc).
	 * @return ResponseEntity<ResponseMessageError>
	 */
	private static ResponseEntity<ResponseMessageError> popularResponseMessageError(Exception e, Integer status, String titulo,
			HttpServletRequest request) {
		ResponseMessageError err = new ResponseMessageError();
		err.setTimestamp(Instant.now());
		err.setStatus(status);
		err.setError(titulo);
		err.setMessage(e.getMessage());
		err.setPath(request.getRequestURI());
		return ResponseEntity.status(status).body(err);
	}
`

`
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ResponseMessageError {
	private Instant timestamp;
	private Integer status;
	private String error;
	private String message;
	private String path;
}
`

2023-08-27 23:55 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/dto/UsuarioDTO.java
> +@Getter
@Data já tem os getters e setters então é redundante colocar o @getter @setter

2023-08-27 23:55 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/dto/CadastroUsuarioDTO.java
> +	@NotBlank
se caso vier vazio ou nulo qual mensagem de erro retorna

2023-08-27 23:55 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/model/Usuario.java
> +
Tem que mapear o status do usuário

2023-08-27 23:55 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/service/cadastro/validacoes/ValidarSeEmailJaEstaCadastrado.java
> +public class ValidarSeEmailJaEstaCadastrado implements ValidacaoCadastro {
Criar método de validação separada é uma ótima ideia, mas somente quando outras classes utilizam do mesmo código, ai então é valido pra o reaproveitamento de código.

2023-08-27 23:55 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/service/cadastro/CadastroService.java
> +		this.validacoes.forEach(v -> v.validar(dto));
Se por acaso a primeira validação falhar ele executa a segunda validação?

2023-08-28 02:16 UTC, moriartynho commented on src/main/java/br/com/agendamento/api/service/cadastro/CadastroService.java
> +		this.validacoes.forEach(v -> v.validar(dto));
Não, porque a exceção interrompe. A menos que tenha testado errado.

2023-08-28 02:17 UTC, moriartynho commented on src/main/java/br/com/agendamento/api/service/cadastro/validacoes/ValidarSeEmailJaEstaCadastrado.java
> +public class ValidarSeEmailJaEstaCadastrado implements ValidacaoCadastro {
Então ée melhor deixar todas as validações no método do cadastro?

2023-08-28 02:32 UTC, moriartynho commented on src/main/java/br/com/agendamento/api/service/cadastro/validacoes/ValidarSeSenhasCoincidem.java
> +			throw new RuntimeException("Senhas não coincidem");
Qual a origem do parâmetro "messages"?

2023-08-29 17:58 UTC, moriartynho commented
Não sei se estou fazendo certo.

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/exceptions/ResolveExceptionHandler.java
> +//	public ResponseEntity<ResponseMessageError> handleInternalError(InternalErrorException e, HttpServletRequest request) {
Se não estiver utilizando remove, evite deixar lixo no codigo.

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/controller/UsuarioController.java
> +public class UsuarioController {
![image](https://github.com/projetoOpenSource/ms-agendamento-tarefa-gp1/assets/63881541/a7b547fa-44a8-49e6-8c8e-fa17719c8762)

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/dto/UsuarioDTO.java
> +	private Long id_usuario;
variáveis no Java deve ser camelCase

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/dto/UsuarioDTO.java
> +	private Long id_status;
variáveis no Java deve ser camelCase

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/exceptions/ResolveExceptionHandler.java
> +import org.springframework.web.bind.annotation.ResponseStatus;
otimize os imports

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/exceptions/ResolveExceptionHandler.java
> +public class ResolveExceptionHandler{
passa essa classe para o pacote handle

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/exceptions/ResponseMessageError.java
> +public class ResponseMessageError {
passa essa classe para o pacote handle

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/model/Usuario.java
> +	private Long id_usuario;
variáveis no Java deve ser camelCase se caso for mapear da base de dados utilize o @Colum

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/model/Usuario.java
> +	private Long id_status;
variáveis no Java deve ser camelCase se caso for mapear da base de dados utilize o @Colum

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/model/Usuario.java
> +public class Usuario {
![image](https://github.com/projetoOpenSource/ms-agendamento-tarefa-gp1/assets/63881541/ae234eeb-7fd3-4257-9219-ff3c24fe7004)

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/service/cadastro/CadastroService.java
> +		repository.save(obj);
{
  "timestamp": "2023-08-28T20:47:17.642752200Z",
  "status": 500,
  "error": "Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection",
  "message": "Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection",
  "path": "/ms-agendamento-tarefa/usuarios"
}

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/controller/UsuarioController.java
> +	public ResponseEntity<UsuarioDTO> cadastrarUsuario(@RequestBody @Valid CadastroUsuarioDTO novoUsuario) throws ValidacaoException{
Use o @RequestBody desse pacote  org.springframework.web.bind.annotation

2023-08-29 19:32 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/controller/UsuarioController.java
> +	public ResponseEntity<UsuarioDTO> cadastrarUsuario(@Valid @RequestBody CadastroUsuarioDTO novoUsuario) throws ValidacaoException{
utilize o @RequestBory do pacote org.springframework.web.bind.annotation

2023-08-29 19:38 UTC, moriartynho commented on src/main/java/br/com/agendamento/api/dto/UsuarioDTO.java
> +	private Long id_usuario;
Peguei o que tava no bd, acabei não me atentando.

2023-08-29 19:45 UTC, moriartynho commented on src/main/java/br/com/agendamento/api/model/Usuario.java
> +public class Usuario {
isso não aparece pra mim

2023-09-03 18:45 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/dto/CadastroUsuarioDTO.java
> +	private String email;
se eu adicionar mais caractere ao criar o email na base dados o que acontece?

2023-09-03 18:45 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/model/Usuario.java
> +
cria a classe model de Status e faça o relacionamento com o usuário com o @manytoone

2023-09-03 18:45 UTC, salatielfiore commented on src/main/java/br/com/agendamento/api/model/Usuario.java
> +	private Long id_Usuario;
camelCase

2023-09-05 23:14 UTC, salatielfiore approved these changes

2023-09-05 23:15 UTC, merged